### ISSUE TITLE
Update builder to make rest api call to franklin-api about status

### ISSUE THREAD

**Issue by JulianGindi** [istrategylabs/franklin#11]

**Comment by oudeismetis** [comment]
I've sort of implemented some of this in my recent PR. There is now 'status' tracked on the site model in franklin_api. It currently has 4 states: 'REGISTERED', 'BUILDING', 'SUCCESS', 'FAILED'.

Registered is only used during initial setup of the project before the first webhook is fired. Building is set after _api successful makes a call over to _builder. If that initial call falls, I set the state to failed. 

Otherwise, all that should be needed is for _builder to make a REST call back over to _api with a success/fail result of the actual deployment. 

When we eventually build an admin panel for managing projects, we can show the current state of all deployments with a nice colorful marker.
