### ISSUE TITLE
".franklin" configuration file

### ISSUE THREAD

**Issue by JulianGindi** [istrategylabs/franklin#64]

**Comment by JulianGindi** [comment]
- Presence of the file means we will build the repo
- Potentially exclude files with regex potentially

**Comment by oudeismetis** [comment]
(The below is mostly a mind dump now that I'd thinking about how this will actually work)

Have begun working on this, but now realize it's kind of a rabbit hole. There are really 2 things in the workflow that we will use this file for. We will search all of your github projects for the presence of the file. If found we will...

1) ingest the yaml file and write some settings to the DB.
2) Make an api call to github to register a webhook. 

Considerations I'm still thinking about:
- Changes to the .franklin file. If a change is made, we'll need a way of detecting that and updating the settings. If we CAN'T do that, we might be forced to fetch the entire repo on the api side for every webhook trigger so we can make a fresh read of the file and make sure we still want to do a deploy. This would not be ideal. Hopefully it doesn't come to that. I don't really like the idea of api cloning repos for every webhook event.
- We may want vague/generic webhooks that get fired for any change in the project. If we try to be specific and targeted with the webhooks (like we discussed with tagging), we could end up in a situation where someone changes how their project is deployed and we never hear about it because we are waiting for a tag event webhook that no longer fires. This is especially true if we can't detect changes to the .franklin file.

**Comment by oudeismetis** [comment]
IMPORTANT:
Discussed this with Abrahams. There is a problem with the current implementation of .franklin file ingestion. As I started building this, I realized that we would have to make git calls to fetch all repo names (2 calls) and then a call to each of those repos to see if they have a .franklin file (currently 166 calls). THEN, we might even need to make that same call for all branches of the repo to cover special cases where .franklin doesn't live in master. (1000+ api call???) Pull on this string long enough, and you come to a realization.

We probably need to build a franklin admin panel. You would log in with github. As a result, we'd generate the oAuth token for our api calls at that point. Then you'd pick the organization you'd want to setup franklin for. We'd then make those 2 api calls to fetch all repos for ISL. You would then be presented with a list of all the repos you can setup. Clicking on one, you'd be asked a couple of small questions like which is your production branch/tag, setup a 2nd/3rd/4th environment, etc. All environment questions would live in the admin panel. Once done, we would then setup the webhook behind the scenes for just that repo and would execute any config settings we happen to find in a .franklin file there. You would then also use the admin panel to follow the status of deploys and do things similar to Travis. 

Environment stuff -> admin panel
Build/Deploy stuff -> .franklin file

Lets discuss...
Ed
